image: node:latest

services:
  - mongo:latest

variables:
  MONGO_INITDB_DATABASE: ak18b

stages:
  - test
  - production

cache:
  paths:
    - Projekt/node_modules/
    - Projekt/client/node_modules/
    - Projekt/client/documentation/
    - Projekt/server/node_modules/

test_client:
  stage: test
  script:
    - cd Projekt/client/
    - npm install
    - npm install @compodoc/compodoc
    - npm run test

test_server:
  stage: test
  script:
    - cd Projekt/server/
    - npm install
    - npm run test

deploy:
  stage: production
  script:
    - cd Projekt/client/
    - npm run compodoc
    - cd Projekt/
    - npm install
    - npm run build:all
    - npm run deploy
  only:
    - master
  when: manual
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - Projekt/dist/
